name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Utilisation de Windows pour l'exécution

    steps:
    # Vérifie le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # Restaure les dépendances
    - name: Restore dependencies
      run: dotnet restore

    # Compile le projet
    - name: Build
      run: dotnet build --no-restore --configuration Release
